#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{times}
#+LATEX_HEADER: \usepackage[super,sort&compres]{natbib}
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+LATEX_COMPILER: pdflatex
#+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK")
#+OPTIONS: date:nil e:t email:nil f:t inline:t num:t p:nil pri:nil
#+OPTIONS: prop:nil stat:t tags:t tasks:t tex:t timestamp:t title:t
#+OPTIONS: toc:nil todo:t |:t
#+TITLE: A simplified view into the dielectric nature of 2D semiconductors
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.3.1 (Org mode 9.1.13)

This script is intended to provide a simple yet predictive model for
the static dielectric nature of 2D materials, with clarification for
some quantities. This would serve as a potential layout for our
revised manuscript.

I have noted the unclear parts in the =TODO= fields. I appreciate your comments.

* The use of the "dielectric constant" for a 2D material

IMHO the definition of a "dielectric constant" for a 2D material is
ambiguous, mainly due to the following reasons:
1) The strict 2D dielectric constant is a function of momentum
   transfer $\mathbf{q}$, and vanishes when $\mathbf{q} \to 0$ cite:Cudazzo_2011_screening_2D.
2) The response function of a 2D materials $\chi^{-1}(z)$ of a 2D
   material is highly inhomogeneous in the z-direction, where the
   dielectric "constant" is ill-defined.

#+CAPTION: Example of the heterogeneity in a 2D material stack (2 layers of MoS2). Left: induced charge density. Right: potential across the 2D stack. Calculated results adapted from the QEH model of the GPAW software.
#+ATTR_LATEX: :width 0.6\linewidth
[[file:img/2_MoS2.pdf]]

** Macroscopic dielectric constant in a 2D superlattice

The macroscopic static dielectric tensor of a simulation cell is defined as (SI):
\begin{equation}
\label{eq:3}
\varepsilon_{ij} = 1 + \frac{\partial P_{i}}{\varepsilon_{0} \partial E_{j}}
\end{equation}

where $P_{i} = {\displaystyle \frac{\Delta \sum u_{i}}{\Delta
\Omega}}$ is the polarization density in direction $i$, where $u_{i}$
is individual dipole projected in direction $i$ and $E_{j}$ is the
"macroscopic" electric field applied in direction $j$. If we model the
dielectric constant of a 2D material in a periodic cell, we shall see
immediately the dielectric constant **decreases** with a larger box
size (in particular, z-direction length), since in $P_{i}$, the total
polarization $\sum u$ remains constant, while $\Delta \Omega$
increases.

** The unchanged properties for a 2D material

If the $\varepsilon$ of the superlattice cannot be used as the
dielectric constant for a 2D material, then what? 

We have several options:
1) Define the "dielectric constant" for a 2D material
2) Use a lattice-invariant property to represent the dielectric nature of 2D material.

From the ab initio calculations we can only calculate the properties
of a defined lattice geometry. Assume a 2D superlattice with
/z/-direction length of L, and the 2D material is embedded parallel to
the xy-direction (Fig. [[ref:fig-2D-stack]]). The fraction of the 2D
material is $f$.  Let's look into the two methods above:

#+CAPTION: The 2D superlattice in x- and z- directions.
#+ATTR_LATEX: :width 0.6\linewidth
#+NAME: fig-2D-stack
[[file:img/2D_stack.pdf]]

*** Redefine the 2D dielectric constant

If it is possible to describe the 2D material as a homogeneous medium
with thickness $d = f L$, then it has a 2D dielectric constant
$\varepsilon_{\mathrm{2D}}$. From the Maxwell-Garnett theory we know
that the effective dielectric constant of the superlattice
$\varepsilon_{\mathrm{3D}}$ is anisotropic cite:Markel_2016:

\begin{eqnarray}
\label{eq:4}
\varepsilon_{\mathrm{3D}}^{\parallel} &= f\varepsilon_{\mathrm{2D}}^{\parallel} + (1-f)\\
1/\varepsilon_{\mathrm{3D}}^{\perp} &= f/\varepsilon_{\mathrm{2D}}^{\perp} + (1-f)
\end{eqnarray}
which is the approach suggested by the reviewer 1.

Although theoretically correct, this approach requires a precise
determination of $f$, and subsequently $d$. As mentioned before the
definition of $d$ is vague, in particular for one-atom-thick materials
like h-BN. Typically one would calculate the macroscopic
$\varepsilon_{\mathrm{SL}}$ as a function of $L$ and perform a
least-square fit for (1) $\epsilon_{\mathrm{2D}}$, (2) $d$. Using the
$\varepsilon$ from the data associated with single $L$ would result in a negative $\varepsilon_{\mathrm{2D}}$, if the estimation of $d$ is incorrect.

We will also show that another macroscopic quantity, the susceptibility
$\chi$, is not a thickness-independent parameter. 
- The xx component 

  In the x-direction, there is no screening of
  electric field, i.e. $E_{\mathrm{2D}}^{x} = E_{\mathrm{v}}^{x} =
  E_{\mathrm{3D}}^{x}$.
  The polarization density in the 2D domain is:
  
  \begin{equation} 
  \label{eq:5}
  P_{\mathrm{2D}}^{x} = \varepsilon_{0} \chi_{\mathrm{2D}}^{xx} E_{\mathrm{2D}}^{x}
  \end{equation}

  The polarization density in the whole unit cell is:
  
  \begin{equation} 
  \label{eq:6}       
  P_{\mathrm{3D}}^{x} = \varepsilon_{0} \chi_{\mathrm{3D}}^{xx} E_{\mathrm{2D}}^{x}
  \end{equation}

  Having $P_{\mathrm{2D}} = 1/f P_{\mathrm{3D}}$, we get:
  
  \begin{equation}
  \label{eq:6}
  \chi_{\mathrm{3D}}^{xx} = f \chi_{\mathrm{2D}}^{xx}
  \end{equation}

- The zz component 

  In the z direction, only the displacement field $D$
  is continuous, i.e.:
  \begin{equation}
  \label{eq:7}
  D_{\mathrm{cell}}^{z} = \varepsilon_{\mathrm{3D}}^{zz} \varepsilon_{0} E_{\mathrm{3D}}^{z}
                        = \varepsilon_{0} E_{\mathrm{2D}}^{z} + P_{\mathrm{2D}}^{z}
                        = \varepsilon_{0} E_{\mathrm{v}}^{z}
  \end{equation}
  The macroscopic field $E_{\mathrm{2D}}^{z}$ is determined by
  $E_{\mathrm{2D}}^{z} = E_{\mathrm{v}}^{z} -
  P_{\mathrm{2D}}^{z}/\varepsilon_{0} = E_{\mathrm{v}}^{z} -
  \chi_{\mathrm{2D}}^{zz} E_{\mathrm{2D}}^{z}$
  cite:Bettini_2016_electromag.  The "effective" electric field in the
  cell $E_{\mathrm{3D}}^{z}$ is the mean-field treatment in the cell
  using potential conservation, which does not exist physically:
  
  \begin{equation}
  \label{eq:8}
  E_{\mathrm{3D}}^{z} = f E_{\mathrm{\mathrm{2D}}}^{z} + (1 - f) E_{\mathrm{v}}^{z}
  \end{equation}

  Comparing Eq. [[ref:eq:7]] and [[ref:eq:8]], and let $\varepsilon_{\mathrm{3D}}^{zz} = 1 + \chi_{\mathrm{3}}$, we have:
  
  
  \begin{equation}
  \label{eq:9}
  \frac{1}{1 + \chi_{\mathrm{3D}}^{zz}} = \frac{f}{1 + \chi_{\mathrm{2D}}^{zz}} + \frac{1-f}{1}
  \end{equation}
  which is essentially the same expression as Eq. [[ref:eq:4]]. A further
  transformation gives the relation between $\chi_{\mathrm{3D}}^{zz}$ and $\chi_{\mathrm{2D}}^{zz}$:
  
  
  \begin{equation}
  \label{eq:10}
  \frac{\chi_{\mathrm{3D}}^{zz}}{1 + \chi_{\mathrm{3D}}^{zz}} 
  = f \left( \frac{\chi_{\mathrm{2D}}^{zz}}{1 + \chi_{\mathrm{2D}}^{zz}}\right)
  \end{equation}

  We see that using the macroscopic quantities $\epsilon$ or $\chi$
  requires the determination of $f$, which couldn't be performed on simulation using single $L$ value.




*** Lattice-independent parameter

Here we will show the polarizability $\alpha$ of a 2D material is the
lattice-independent parameter we seek. Inspired by the fact that the
polarizability of a molecule is simply the characteristic of the
volume of electron cloud cite:Israelachvili_2011, the polarizability
of an extended system may also be related with the "volume" of 2D
material, that is independent of the lattice size.

Start from the polarization density $P$, let's still assume that the
2D material has a thickness of $d$, $P_{\mathrm{2D}}$ and
$P_{\mathrm{3D}}$ (components in all directions) can be expressed as:
\begin{eqnarray}
\label{eq:11}
P_{\mathrm{2D}} &= {\displaystyle \frac{\sum_{\Omega_{\mathrm{2D}}} u}{\Omega_{\mathrm{2D}}} 
                 = {\displaystyle \frac{\sum_{\Omega_{\mathrm{2D}}} u}{S_{\mathrm{cell}} d}  & \\
P_{\mathrm{3D}} &= {\displaystyle \frac{\sum_{\Omega_{\mathrm{3D}}} u}{\Omega_{\mathrm{3D}}} 
                 = {\displaystyle \frac{\sum_{\Omega_{\mathrm{3D}}} u}{S_{\mathrm{cell}} L}  & \\
\end{eqnarray}
where $\sum_{\Omega} u = \int_{\Omega} \rho(z) z dz$.  Since we know
the dipole moment $u$ only contains in the 2D domain, essentially
$\sum_{\Omega_{\mathrm{2D}}} u = \sum_{\Omega_{\mathrm{3D}}}
u$. Therefore, the value $\mu = \sum_{\Omega_{\mathrm{3D}}}
u/S_{\mathrm{cell}}$, i.e. the slab polarization density, is
*independent* of the lattice size.

Similar to the definition of molecular polarizability, $\alpha_{ij} =
u_{i}/E_{j}$, we can define the polarizability of a 2D material as:

\begin{equation}
\label{eq:12}
\alpha_{\mathrm{2D}}^{ij} = \frac{\mu_{\mathrm{2D}}^{i}}{E_{\mathrm{loc}}^{j}}
\end{equation}

Here the Lorentz "local" field $E_{\mathrm{loc}}$ is used. Treating
the 2D material as a slab, in the xy-direction
$E_{\mathrm{loc}}^{x}=E_{v}^{x}$, while in the z-direction the dipole
layer of 2D material gives $E_{\mathrm{loc}}^{z} = E_{v}^{z} +
\frac{\mu_{\mathrm{2D}}}{\varepsilon_{0} L}$
cite:Meyer_2001_dipole_slab. Plug this into Eq. [[ref:eq:12]], we have:

\begin{equation}
\label{eq:13}
E_{\mathrm{loc}}^{z} = \frac{E_{\mathrm{v}}^{z}}{1 - \frac{\alpha_{\mathrm{2D}}^{zz}}{\varepsilon_{0} L}}
\end{equation}

Using the definition of $\varepsilon_{ij}$ in Eq. [[ref:eq:3]], we can
convert the $\alpha_{\mathrm{2D}}$ back to
$\varepsilon_{\mathrm{3D}}$. Note that within the Berry phase response
method, the $E$ used is actually $E_{v}$ cite:Meyer_2001_dipole_slab:

\begin{eqnarray}
\label{eq:14}
\varepsilon_{\mathrm{3D}}^{xx} &= 1 + \frac{\alpha_{\mathrm{2D}}^{xx}}{\varepsilon_{0} L} \\
\label{eq:15}
\varepsilon_{\mathrm{3D}}^{zz} &= \left(1 - \frac{\alpha_{\mathrm{2D}}^{zz}}{\varepsilon_{0} L}\right)^{-1}
\end{eqnarray}

And we see now the $\varepsilon_{\mathrm{3D}}$ calculated from DFT can
be related with $\alpha_{\mathrm{2D}}$, and only one parameter $L$ is
needed.

If we like, we can also use the 2D polarizability to "reconstruct" the
"2D dielectric constant", given the thickness $d$:
\begin{eqnarray}
\label{eq:16}
\varepsilon_{\mathrm{2D}}^{xx}(d) &= 1 + \frac{\alpha_{\mathrm{2D}}^{xx}}{\varepsilon_{0} d} \\
\label{eq:17}
\varepsilon_{\mathrm{2D}}^{zz}(d) &= \left(1 - \frac{\alpha_{\mathrm{2D}}^{zz}}{\varepsilon_{0} d}\right)^{-1}
\end{eqnarray}

It is easy to prove that such $\epsilon_{\mathrm{2D}}$ obeys the
relation in Eq. [[ref:eq:4]]. 

* Some data analysis
The section serves as proof for my proposed approach to use
polarizability as the stem of the dielectric nature of 2D
semiconductors.

** Failure of using the $\varepsilon_{\mathrm{2D}}$ from the effective medium theory 

As seen previously, the $\varepsilon_{\mathrm{2D}}$ calculated from a
single point DFT data will result in a negative result. 

#+CAPTION: Comparison between the rescaled $\varepsilon_{\mathrm{2D}}$ and original $\varepsilon_{\mathrm{SL}}$ from previous calculations. Top: $\varepsilon^{xx}$, bottom: $\varepsilon^{zz}$. Apparently the $\varepsilon_{zz}$ becomes negative for some materials.
#+ATTR_LATEX: :width 0.4\linewidth
[[file:img/comparison_rescale.pdf]]
*************** TODO Need to extract the data using Declan's newest data
*************** END


** Convergence of $\alpha$ as a function of lattice size

First we want to see if using /L/-dependent $\varepsilon$ data gives
converged $\varepsilon$ after rescaling. The tests were performed
based on Declan's data of $\varepsilon_{\mathrm{3D}}$ of MX2 with
varying $L$ values. The values $\varepsilon_{\mathrm{2D}}^{xx}$,
$\varepsilon_{\mathrm{2D}}^{zz}$ and $d$ were fitted by
Eq. [[ref:eq:4]]. The negative $\varepsilon^{zz}$ problem can be solved,
with an error of ca. 5% for the $d$ predicted from $x$ and $z$
directions. However we immediately see that
$\varepsilon^{zz}_{\mathrm{2D}}$ for some materials (WTe2) are even
larger then $\varepsilon_{\mathrm{2D}}^{xx}$, which is unphysical.

#+CAPTION: Fitted values of $\varepsilon_{\mathrm{2D}}$ and $d$ using /L/-dependent $\varepsilon_{\mathrm{3D}}$ data of MX2 materials. 
[[file:img/Declan_L_eps_rescale.pdf]]


When we use Eqs. [[ref:eq:14]] and [[ref:eq:15]] to convert
$\varepsilon_{\mathrm{3D}}$ to $\alpha$, we can see that with $L>15\
\AA$, the calculated $\alpha$ values both in-plane and out-of-plane
are independent of $L$. Fig. [[ref:fig-alpha-converg]] shows the case for
MoS2. The /L/-independent property of $\alpha$ is observed also for all other MX2 materials.

#+CAPTION: Convergence of $\alpha$ w.r.t. $L$ for MoS2. Meanwhile the $\varepsilon$ is not converged.
#+NAME: fig-alpha-converg
[[file:img/alpha_convergence_MoS2.pdf]]

We can therefore use the $\varepsilon$ of a 2D superlattice calculated
on single $L$ value, to extract the value of $\alpha$.

** The physical meanings of $\alpha$

Since I don't have the new data in hand, I made my data analysis using
the GPAW datasets (https://cmrdb.fysik.dtu.dk/?project=c2db) in which
the dielectric properties were calculated on the PBE xc. The data were
further validated on the Euler cluster which gives the same results.
*************** TODO Essentially we need to answer why we use the HSE functional in VASP for the dielectric properties. What is the advantage over GGA?
*************** END
By extracting the 2D polarizabilities over 200 2D materials with GW
bandgap \lt{}0.5 eV, the relation of $\alpha_{\mathrm{2D}}^{xx}$ and
$\alpha_{\mathrm{2D}}^{zz}$ w.r.t to the HSE bandgap is shown in
Fig. [[ref:fig-alpha-original]]

#+CAPTION: $\alpha_{\mathrm{2D}}^{xx}$ (left) and $\alpha_{\mathrm{2D}}^{zz}$ (right) as functions of HSE bandgap in the whole GPAW dataset.
#+NAME: fig-alpha-original
[[file:img/alpha_Eg_original.pdf]] $\alpha_{\mathrm{2D}}^{xx}$ seems to
have a inverse power relation with $E_{\mathrm{g}}$, while the
relation for $\alpha_{\mathrm{2D}}^{zz}$ with $E_{\mathrm{g}}$ is not
clear (a decreasing trend with large deviation). Next I'll try to
explain the physical meaning of both components.

*** $\alpha_{\mathrm{2D}}^{xx}$
From the two-band model proposed by Jiang et
al. cite:Jiang_2017_Eg_Eb, when mapping the 3D response function to an
2D plane, the 2D in-plane polarizability is a dominated by the states
near the cbm and vbm, as described from the RPA theory and Lindhard function:
\begin{equation}
\label{eq:alpha-jiang}
\begin{aligned}
\alpha_{\mathrm{2D}}^{xx} &= (4 \pi \varepsilon_{0}) \frac{\varepsilon_{\mathrm{3D}} - 1}{4 \pi L} \\
                          &= (4 \pi \varepsilon_{0}) \frac{2e^{2}}{(2\pi)^{2}} \sum_{cv} \int_{\mathrm{BZ}} 
                             \frac{|<\psi_{c,k}|\nabla_{k}|\psi_{v,k}>|^{2}}{E_{c,k}} - E_{v,k}} d^{2}k \\
                          &= (4 \pi \varepsilon_{0}) \frac{2e^{2}}{(2\pi)^{2}} N_{\mathrm{g}} \int_{0}^{k_{BZ}} \frac{\hbar^{2}}{2m^{*}} \frac{2\pi k}{(E_{g} + \hbar^{2} k^{2}/(2 m^{*}))^{2}} dk \\
                          &\approx (4 \pi \varepsilon_{0}) \frac{e^{2}}{2 \pi E_{g}}
\end{aligned}
\end{equation}
where c and v are the conduction and valence bands, BZ is the first
Brillouin Zone, $N_{g}$ is the degeneracy of CB bands, and $m^{*}$ is
the effective mass near the band valley. This result points out the
potential relation between $\alpha^{xx}$ and $E_{g}$ in a 2D
crystal. It should be noted, by applying the same procedure to a 3D
polarizability (susceptibility) $\alpha_{3D}$ following Eq. [[ref:eq:17]],
it looks like:
\begin{equation}
\label{eq:1}
\begin{aligned}
\alpha_{\mathrm{3D}} &= (4\pi \epsilon_{0}) \frac{\varepsilon_{\mathrm{3D}} -1}{4 \pi} \\
                     &\propto \sum_{cv} \int_{\mathrm{BZ}} 
                             \frac{|<\psi_{c,k}|\nabla_{k}|\psi_{v,k}>|^{2}}{E_{c,k}} - E_{v,k}} d^{3}k \\
                     &\propto \int_{0}^{k_{BZ}} \frac{\hbar^{2}}{2m^{*}} \frac{4\pi k^{2}}{(E_{g} + \hbar^{2} k^{2}/(2 m^{*}))^{2}} dk
\end{aligned}
\end{equation}
Following the assumption that $\hbar k_{\mathrm{BZ}}$ is much larger
than $E_{\mathrm{g}}$, this integral gives that (see [[http://www.wolframalpha.com/input/?i=integral+4+*+pi+*+x%255E2%252F(A%252BBx%255E2)%255E2++dx]]):
\begin{equation}
\label{eq:18}
\alpha_{\mathrm{3D}} \propto \frac{2\pi \sqrt{m^{*}}}{\hbar \sqrt{E_{g}}}
\end{equation}
this different power law is close to the 3D Moss relation. The
interesting property that by mapping polarizability to 2D, the
$\alpha-E_{\mathrm{g}}$ relation is independent of effective mass $m^{*}$.

*************** TODO I think the power law for 3D $E_{g}$ and $m^{*}$ in Eq. [[ref:eq:18]] is similar to Eq. A9 in Ref citenum:Finkenrath_1988, which is a good indication. However from the Drude-Lorentz model a bulk material possesses $\alpha \propto 1/(m^{*} E_{g}^{2})$. Can we solve this dilemma? 
*************** END

Now let's test the $\alpha-E_{g}$ relation. Again the dataset was taken from the GPAW repository. Plotting $\alpha_{\mathrm{2D}}^{xx}$ against $1/E_{\mathrm{g}}$ shows that most materials are scattered along the diagonal line (Fig. [[ref:fig-alpha-2D-Eg-full]]):
#+CAPTION: $\alpha_{\mathrm{2D}}^{xx}$ as a function of $1/E_{g}$ (HSE) for all the materials
#+NAME: fig-alpha-2D-Eg-full
#+ATTR_LATEX: :width 0.5\linewidth
[[file:img/alpha_xx_1_Eg.pdf]]

If we further focus on the 2D materials in Dale's dataset, we can draw
a linear regression of $\alpha-E_{g}^{-1}$ relation (Fig. [[ref:fig-alpha-2D-Eg-subset]])
#+CAPTION: $\alpha_{\mathrm{2D}}^{xx}$ as a function of $1/E_{g}$ (HSE) for materials studied in this paper
#+NAME: fig-alpha-2D-Eg-subset
#+ATTR_LATEX: :width 0.5\linewidth
[[file:img/alpha_xx_1_Eg_subset.pdf]]

Considering that the in-plane polarizability has magnitude of $10^{1}
\sims 10^{2}$ \AA\(\cdot \varepsilon_{0}\), the intercept of 0.47
indicates good linear relation between the two quantities. 

*************** TODO Another thought, since $\alpha_{\mathrm{2D}}$ has unit of [Length]*[\(\varepsilon_{0}\)], is it possible that $\alpha_{\mathrm{2D}}$ is the characteristic length in-plane, i.e. the Bohr radius?
*************** END

*** $\alpha_{\mathrm{2D}}^{zz}$

For $\alpha_{\mathrm{2D}}^{zz}$ the relation with $E_{g}$ is not
apparent. It can be revealed by combining Eqs. [[ref:eq:17]] and
[[ref:eq:alpha-jiang]] (detailed procedure not shown). However, recall
that the dimension analysis of $\alpha_{\mathrm{2D}}$ gives the unit
of [Length]*[\(\varepsilon_{0}\)], it is highly possible that
$\alpha_{\mathrm{2D}}^{zz}$ is a characteristic length in the
z-direction, since the electrons are confined, and behaves more like
isolated molecules. We propose one possible characteristic z-length
for 2D materials, the covalent thickness, i.e. the distance between
the outermost covalent electron shell of all atoms in the z-direction:
\begin{equation}
\label{eq:d-cova}
d_{\mathrm{cov}} = \mathrm{max}(z_{i} + r_{\mathrm{cov}}_{i}) - \mathrm{min}(z_{i} - r_{\mathrm{cov}}_{i})
\end{equation}
where i iterate over the atoms, and $r_{\mathrm{cov}}$ is the covalent
radius of the atom. Indeed the $\alpha_{\mathrm{2D}}^{zz}$ shows a
strong relation with $d_{\mathrm{cov}}$ (Fig. [[ref:alpha-zz-d]]):

#+CAPTION: $\alpha_{\mathrm{2D}}^{zz}$ as a function of $d_{\mathrm{cov}}$ for all the materials
#+NAME: alpha-zz-d
#+ATTR_LATEX: :width 0.5\linewidth
[[file:img/alpha_zz_thick.pdf]]

Again analyzing the materials presented in this paper we get a quite
strong linear correlation with $R^{2} = 0.97$ (Fig. [[ref:alpha-zz-d-sub]])

#+CAPTION: $\alpha_{\mathrm{2D}}^{zz}$ as a function of $d_{\mathrm{cov}}$ for materials in this paper.
#+NAME: alpha-zz-d-sub
#+ATTR_LATEX: :width 0.5\linewidth
[[file:img/alpha_zz_thick_subset.pdf]]

I think the explanation of $\alpha_{\mathrm{2D}}^{zz}$ is reasonable,
and seems no one has studied it before.

Combining this result with Eqs. [[ref:eq:17]], we can see that the
$\varepsilon_{\mathrm{2D}}$, if exists, is a geometric-dominated
quantity.


* References
[[bibliography:ref.bib]]
[[bibliographystyle:achemso]]
